meta:
  name: desct-test-new
  project: desct
  tags: []
  experiment_folder: experiment
data:
  module: datasets.modelnet
  root: ./data/modelnet_aligned_40_1000
  num_workers: 0
  batch_size: 64
  pin_memory: true
  name: '40'
  samplepoints: 1000
model:
  module: models.deepsets
  d_dim: 256
  x_dim: 3
  pool: mean
  num_classes: 40
trainer:
  lr: 0.001
  num_epochs: 1000
