meta:
  name: desct-test-new
  project: desct
  tags: []
  experiment_folder: experiment
data:
  module: datasets.gnn_benchmark
  root: ./data
  num_workers: 0
  batch_size: 512
  pin_memory: false
  name: MNIST
model:
  module: models.ect_cnn_points
  num_thetas: 32
  bump_steps: 32
  batch_size: 128
  R: 1.1
  num_features: 3
  num_classes: 10
  hidden: 100
trainer:
  lr: 0.0001
  num_epochs: 100
