meta:
  name: desct-test-new
  project: desct
  tags: []
  experiment_folder: experiment
data:
  module: datasets.tu
  root: ./data
  num_workers: 0
  batch_size: 32
  pin_memory: true
  drop_last: false
  name: DD
  cleaned: true
  use_node_attr: true
model:
  module: models.ect_best_model
  num_thetas: 128
  bump_steps: 128
  batch_size: 128
  R: 1.1
  num_features: 89
  num_classes: 2
  hidden: 100 
trainer:
  lr: 0.0001
  num_epochs: 60
