meta:
  name: desct-test-new
  project: desct
  tags: []
  experiment_folder: experiment
data:
  module: datasets.modelnet
  root: ./data/modelnet_aligned_40_100
  num_workers: 0
  batch_size: 128
  pin_memory: true
  name: '40'
  samplepoints: 100
model:
  module: models.ect_best_model
  num_thetas: 64
  bump_steps: 128
  R: 1.2
  num_features: 3
  num_classes: 40
  hidden: 200
trainer:
  lr: 0.0001
  num_epochs: 100
