wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684520936.253683
    t:
      1:
      - 1
      - 9
      - 41
      - 51
      - 55
      - 77
      2:
      - 1
      - 9
      - 41
      - 51
      - 55
      - 77
      3:
      - 13
      - 23
      4: 3.11.3
      5: 0.15.3
      8:
      - 5
