data:
  name: ModelNetDataModule
  config:
    root: ./data
    batch_size: 256
    num_workers: 16
    samplepoints: 100

model:
  name: ECTPointsLinearModel
  config:
    bump_steps : 20
    num_thetas : 30
    num_features : 3
    R : 1.5
    scale : 200
    hidden: 100
    num_classes: 10

trainer:
  lr: 0.0001
  num_epochs : 1
