data:
  name: GNNBenchmarkDataModule
  config:
    name: MNIST
    root: ./data
    batch_size: 256
    num_workers: 16
    split: train
model:
  name: ECTPointsLinearModel
  config:
    bump_steps: 10
    num_thetas: 10
    num_features: 3
    R: 1.5
    scale: 500
    num_classes: 10
    hidden: 10
trainer:
  lr: 0.001
  num_epochs: 200
